// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS5DB-PuKWqV7IrUQPQ6VGQg-A_TKRz44',
    appId: '1:431491551192:web:trendafrontendweb123456',
    messagingSenderId: '431491551192',
    projectId: 'trendalocal',
    authDomain: 'trendalocal.firebaseapp.com',
    storageBucket: 'trendalocal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS5DB-PuKWqV7IrUQPQ6VGQg-A_TKRz44',
    appId: '1:431491551192:android:3eddb4c1044697caea6cad',
    messagingSenderId: '431491551192',
    projectId: 'trendalocal',
    storageBucket: 'trendalocal.firebasestorage.app',
  );

  // The iOS app registered in Firebase (trendalocal › iosApps). The appId used
  // to be a made-up placeholder, so Firebase could not start on an iPhone.
  // Values match ios/Runner/GoogleService-Info.plist — change both together.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdXIzMCLotS5NOxNKPee3Cfqz2QRfElI',
    appId: '1:431491551192:ios:d5a53eb77007389cea6cad',
    messagingSenderId: '431491551192',
    projectId: 'trendalocal',
    storageBucket: 'trendalocal.firebasestorage.app',
    iosClientId:
        '431491551192-dl1tegh18bvd4drae76t10trtom1quto.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendaFrontend',
  );
}
